---

- name: Download binary package
  get_url:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "~/go{{ go_version }}.linux-amd64.tar.gz"

- name: Extract files
  unarchive:
    src: "~/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: Check zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_result

- name: Add env to zshrc
  lineinfile:
    path: ~/.zshrc
    insertafter: EOF
    line: "\n# Golang\nexport PATH=$PATH:/usr/local/go/bin"
  when: stat_result.stat.exists

- name: Check bashrc exists
  stat:
    path: ~/.bashrc
  register: stat_result

- name: Add env to bashrc
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    line: "\n# Golang\nexport PATH=$PATH:/usr/local/go/bin"
  when: stat_result.stat.exists

- name: Check go
  command: /usr/local/go/bin/go version
