---

- name: Download install.sh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/install.sh

# - name: Install oh-my-zsh
#   script: ~/install.sh

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Push zshrc
  copy:
    src: zshrc
    dest: ~/.zshrc
